apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T08:45:04Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "9626"
  uid: 78b2494d-6233-4c7a-b166-0a6cbc13c36e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.223.160
  clusterIPs:
  - 10.96.223.160
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32712
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
