apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T10:22:47Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "521"
  uid: 67c36946-9ed7-43f6-9374-c665860e5aa6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.99.19
  clusterIPs:
  - 10.98.99.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31112
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
